// scripts/generate-sitemap.js
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Resolve the site URL from environment variables.
 * Priority:
 *   1. PUBLIC_SITE_URL (set in Vercel project settings / .env)
 *   2. SITE_URL (generic fallback)
 *   3. Hardcoded default (current production URL)
 *
 * Trailing slashes are stripped so route paths can be safely concatenated.
 */
function resolveBaseUrl() {
  const raw =
    process.env.PUBLIC_SITE_URL ?? process.env.SITE_URL ?? 'https://fact-checklist.vercel.app';
  const trimmed = raw.trim().replace(/\/+$/, '');

  if (!process.env.PUBLIC_SITE_URL && !process.env.SITE_URL) {
    console.warn(
      `⚠️  PUBLIC_SITE_URL is not set. Falling back to default: ${trimmed}\n` +
        '   Set PUBLIC_SITE_URL in your environment (or Vercel project settings) to override.'
    );
  }

  return trimmed;
}

/**
 * Load per-route lastmod dates generated by scripts/get-git-lastmod.js.
 * Returns an empty object when the file is missing (e.g. first build).
 */
function loadLastmodMap() {
  const lastmodPath = path.join(__dirname, '../src/lib/data/git-lastmod.json');
  if (!fs.existsSync(lastmodPath)) {
    console.warn(
      '⚠️  git-lastmod.json not found. Falling back to today for all routes.\n' +
        '   Run `npm run generate:git-lastmod` before this script for accurate lastmod values.'
    );
    return {};
  }

  try {
    const content = fs.readFileSync(lastmodPath, 'utf8');
    return JSON.parse(content);
  } catch (err) {
    console.warn(`⚠️  Failed to parse git-lastmod.json: ${err.message}`);
    return {};
  }
}

/**
 * Look up the lastmod for a route with trailing-slash tolerance,
 * falling back to today's date when no git history is available.
 */
function resolveLastmod(routePath, lastmodMap, fallbackDate) {
  const variants = [
    routePath,
    routePath.replace(/\/$/, ''),
    routePath.endsWith('/') ? routePath : `${routePath}/`
  ];
  for (const key of variants) {
    if (lastmodMap[key]) return lastmodMap[key];
  }
  return fallbackDate;
}

const BASE_URL = resolveBaseUrl();
const routes = [
  { path: '/', priority: '1.0', changefreq: 'weekly' },
  { path: '/intro/', priority: '0.9', changefreq: 'monthly' },
  { path: '/about/', priority: '0.8', changefreq: 'monthly' },
  { path: '/help/', priority: '0.7', changefreq: 'monthly' },
  { path: '/privacy/', priority: '0.5', changefreq: 'yearly' }
];

function generateSitemap() {
  const fallbackDate = new Date().toISOString().split('T')[0];
  const lastmodMap = loadLastmodMap();

  const sitemapContent = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${routes
  .map(route => {
    const lastmod = resolveLastmod(route.path, lastmodMap, fallbackDate);
    return `  <url>
    <loc>${BASE_URL}${route.path}</loc>
    <lastmod>${lastmod}</lastmod>
    <changefreq>${route.changefreq}</changefreq>
    <priority>${route.priority}</priority>
  </url>`;
  })
  .join('\n')}
</urlset>
`;

  const sitemapPath = path.join(__dirname, '../static/sitemap.xml');
  fs.writeFileSync(sitemapPath, sitemapContent);
  console.warn(`✅ sitemap.xml generated (base: ${BASE_URL}, routes: ${routes.length})`);
}

generateSitemap();
